name = "RiemannZeta"
version = "0.1.0"
keywords = ["math", "number-theory", "riemann-hypothesis"]
defaultTargets = ["Riemann"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3


[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "v4.27.0-rc1"

[[require]]
name = "lean4checker"
scope = "leanprover"
rev = "bump_to_v4.27.0-rc1"

[[lean_lib]]
name = "Riemann"
